FROM php:8.0.9-fpm-alpine

RUN docker-php-ext-install pdo pdo_mysql

#RUN chmod -R 777 /var/www/html/storage/logs/laravel.log
#RUN chmod -R 755 /var/www/html/public/avatars
#RUN chmod -R 755 /var/www/html/public/product