version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: shop_nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./src:/var/www/html
      - ./services/production/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - shop_network
    restart: always
  mysql:
    image: mysql:8.0.26
    container_name: shop_mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./services/production/mysql:/var/lib/mysql
    networks:
      - shop_network
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: mysql
  php:
    build:
      context: .
      dockerfile: ./services/production/php/Dockerfile
    container_name: shop_php
    volumes:
      - ./src:/var/www/html
    networks:
      - shop_network
    restart: always
  phpmyadmin:
    build:
      context: .
      dockerfile: ./services/production/phpmyadmin/Dockerfile
    container_name: shop_phpmyadmin
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
    networks:
      - shop_network
    restart: always
networks:
  shop_network: